@TallerBackend_HostAddress = http://localhost:5018
@token = pega_aqui_el_token

POST {{TallerBackend_HostAddress}}/api/auth/primer-admin
Content-Type: application/json

{
  "nombre": "Administrador",
  "username": "admin",
  "correo": "admin@taller.com",
  "password": "Admin12345"
}

###

POST {{TallerBackend_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "usuarioOCorreo": "admin",
  "password": "Admin12345"
}

###

GET {{TallerBackend_HostAddress}}/api/roles
Accept: application/json
Authorization: Bearer {{token}}

###

GET {{TallerBackend_HostAddress}}/api/usuarios
Accept: application/json
Authorization: Bearer {{token}}

###

GET {{TallerBackend_HostAddress}}/api/vehiculos
Accept: application/json
Authorization: Bearer {{token}}

###

POST {{TallerBackend_HostAddress}}/api/vehiculos
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "placa": "P123ABC",
  "marca": "Toyota",
  "modelo": "Corolla",
  "anio": 2020,
  "kilometraje": 45000,
  "activo": true
}

###

PUT {{TallerBackend_HostAddress}}/api/vehiculos/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "placa": "P123ABC",
  "marca": "Toyota",
  "modelo": "Corolla",
  "anio": 2020,
  "kilometraje": 45500,
  "activo": true
}

###

PATCH {{TallerBackend_HostAddress}}/api/vehiculos/1/estado?activo=false
Authorization: Bearer {{token}}

###
